version: "3.8"
services:
  simplecrudapp:
    image: antoniosai/simple-crud-app:1.0.0
    build: .
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - dbapp
    networks:
      - simpleappnetwork
    environment:
      spring.datasource.url: jdbc:postgresql://dbapp:5432/postgres
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.jpa.hibernate.ddl.auto: create
  dbapp:
    image: postgres:15.1
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    networks:
      - simpleappnetwork
networks:
  simpleappnetwork: