server:
  port: 8001
spring:
  application:
    name: simple-crud-app
    version: 1.0.0
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      idle-timeout: 5000
      max-lifetime: 10000
      maximum-pool-size: 10
      minimum-idle: 3
      schema: school
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS